feat: ready for fist review
VlaPol/TMS_Lesson_17 pull request #1
Opened 2023-03-02 21:09 UTC by VlaPol

2023-03-03 08:32 UTC, grigo-oleg requested changes

2023-03-03 08:32 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
> +    private static Post[] postHistory;
Зачем понадобилось делать static?

Вообще глобальные (static) изменяемые переменные – это антипаттерн. Особенно в коде, описывающем бизнес-логику

2023-03-03 08:32 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
> +            messageCounter++;
Код в else ветке отработает корректно и для пустой истории сообщений. Этот if можно удалить

2023-03-03 08:32 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
> +        }
Какая цель этого кода?

2023-03-03 08:32 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
> +            }
В массиве сообщения хранятся в хронологическом порядке. Нам нет смысла проверять всю историю. Достаточно проверить сообщения из rate limiting промежутка времени. Также нет смысла продолжать подсчёт, если мы уже достигли rate limiting максимума

2023-03-03 08:32 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
> +    public boolean addNewPost(Post newPost) {
PostService описывает бизнес-логику и отвечает за её полное соблюдение. Post содержит модель бизнес-данных. Некоторые элементы этой модели должны подчиняться определённым правилам. Например, момент создания сообщения должен быть зафиксирован через Instant.now(). Мы не доверяем вызывающей стороне. Да, она может при создании объекта Post действительно передать Instant.now() для messageTime. Но технически может передать и произвольный момент времени из прошлого/будущего. Гарантировать правильность этой бизнес-логики мы можем только если зададим messageTime здесь, внутри сервиса.
В общем случае мы не принимаем модели данных параметрами при операциях создания/модификации. Мы принимаем недостающие данные через параметры. В нашем случае это содержание сообщения и информация об авторе. Внутри метода мы сами создаём объект модели данных. При этом мы делаем нужную валидацию и собираем дополнительные данные. Дополнительные данные, которые нам не сообщает вызывающая сторона – messageTime

2023-03-03 08:32 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
> +                if (itm.getMessageTime().isAfter(Instant.now().minus(duration))
На каждой итерации Instant.now() будет выдавать новое значение. То есть на каждой итерации мы будем проверять разный промежуток времени. А в объекте Post поле messageTime будет иметь вообще другое значение. Правильнее один раз получить Instant.now() в методе, сохранить его в переменную и использовать и при проверке, и для messageTime

2023-03-03 08:32 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
> +    private final Duration duration;
Не очень говорящие названия. Человек, не знакомый с требованиями по rate limiting, не поймёт по названию, для чего используются эти поля

2023-03-03 08:32 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/Post.java
> +    private final Instant messageTime;
Обычно в названии специфицируют, что именно за время. Что-то плана "created", "createdDateTime", "createdInstant", "createdTimestamp", "createdAt"...

2023-03-03 08:36 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +        }
Обнулить счетчик, если прошло время. По заданию не было, это скорее для законченности

2023-03-03 10:00 UTC, oleg-grigorijan commented on src/by/tms/lesson17/homework/PostService.java
> +        }
Так messageCounter – это локальная переменная. Она у тебя уже 0 при объявлении

2023-03-03 10:58 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +    private static Post[] postHistory;
Согласен, упустил.

2023-03-03 11:01 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +            messageCounter++;
Не проверил, согласен. Исправил

2023-03-03 11:07 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +        }
упс, вот что значит ночью писать ). да, согласен, этот код ничего не делает. удали

2023-03-03 11:25 UTC, VlaPol commented on src/by/tms/lesson17/homework/Post.java
> +    private final Instant messageTime;
подправил

2023-03-03 11:28 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +    private final Duration duration;
подправил, как вижу.

2023-03-03 11:44 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +                if (itm.getMessageTime().isAfter(Instant.now().minus(duration))
да, тут не подумал. исправил

2023-03-03 11:48 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +    public boolean addNewPost(Post newPost) {
Не задумывался над этим. Но учту на будущее.

2023-03-03 11:49 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +            }
тут идей нет, ничего не придумал лучше чем перебирать в обратном порядке, т.к. да, в прямом слишком много будет лишних действий.

2023-03-03 19:59 UTC, oleg-grigorijan requested changes

2023-03-03 19:59 UTC, oleg-grigorijan commented on src/by/tms/lesson17/homework/PostService.java
> +            if (postHistory[i].getMessageTime().isAfter(messageTime.minus(postDelayDuration))
messageTime.minus(postDelayDuration) теперь не зависит от итерации цикла. Чтобы не вычислять одно и то же значение постоянно, можем вынести это в переменную за цикл

2023-03-03 19:59 UTC, oleg-grigorijan commented on src/by/tms/lesson17/homework/PostService.java
> +            if (postHistory[i].getMessageTime().isAfter(messageTime.minus(postDelayDuration))
Если postHistory[i].getMessageTime().isAfter(messageTime.minus(postDelayDuration) – false, то мы можем сделать break и не проверять более старые сообщения

2023-03-03 19:59 UTC, oleg-grigorijan commented on src/by/tms/lesson17/homework/PostService.java
> +        if (messageCounter < limitPostsFromOneUserPerDuration) {
Мы уже делаем return false, если достигли максимума. Тут это можно уже не проверять

2023-03-03 19:59 UTC, oleg-grigorijan commented on src/by/tms/lesson17/homework/PostService.java
> +        return postHistory;
Чтобы вызывающая сторона не могла в обход методов сервиса изменить элементы поля postHistory, желательно не отдавать наружу его адрес. Arrays.copyOf(...)

2023-03-03 20:08 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +        return postHistory;
дополнил

2023-03-03 20:12 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +        if (messageCounter < limitPostsFromOneUserPerDuration) {
исправил

2023-03-03 20:14 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
> +            if (postHistory[i].getMessageTime().isAfter(messageTime.minus(postDelayDuration))
да, согласен, лишнее. испарвил

2023-03-10 07:37 UTC, oleg-grigorijan requested changes

2023-03-10 07:37 UTC, oleg-grigorijan commented on src/by/tms/lesson17/homework/PostService.java
> +                if(postHistory[i].getMessageTime().isBefore(deltaTime)){
Чтобы дойти до этого if, сначало нужно пройти `postHistory[i].getMessageTime().isAfter(deltaTime)` оборачивающего if'а. В итоге это условие всегда будет false. В итоге мы всегда будем проверять всю историю сообщений.
И автоформатирование

2023-03-10 08:31 UTC, oleg-grigorijan approved these changes

2023-03-10 08:31 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
>              if (postHistory[i].getMessageTime().isAfter(deltaTime)
Раз мы сделали break на isBefore, мы можем уже не проверять isAfter. Оно всегда будет true (если не считать очень маловероятную ситуацию, когда два instant'а будут равны)

2023-03-10 08:34 UTC, VlaPol commented on src/by/tms/lesson17/homework/PostService.java
>              if (postHistory[i].getMessageTime().isAfter(deltaTime)
в принципе, да. при такой композиции вторая проверка не нужна, но раз есть хотя бы теоретическая вероятность, то, наверное лучше перебдеть)

2023-03-10 08:34 UTC, merged

2023-03-10 08:35 UTC, grigo-oleg commented on src/by/tms/lesson17/homework/PostService.java
>              if (postHistory[i].getMessageTime().isAfter(deltaTime)
Нам просто не так принципиально равенство, когда мы говорим о моменте времени. Потому что это наносекунды. Бизнесу обычно всё равно на наносекунды. Так что здесь можно было спокойно убирать вторую проверку